#!/bin/bash

docker run --name neutrino-elements-test -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres
sleep 3
docker exec neutrino-elements-test createdb --username=root --owner=root neutrino-elements-test
docker exec neutrino-elements-test createdb --username=root --owner=root neutrino-elements
